import "~/styles/globals.css";

import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";
import { ThemeProvider } from "~/components/theme-provider";
import { SiteHeader } from "~/components/site-header";
import { QueryClientProvider } from "~/components/query-client-provider";
import React from "react";

export const metadata: Metadata = {
  title: "Binance",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html
      lang="vi"
      className={`${GeistSans.variable}`}
      suppressHydrationWarning
    >
      <body>
        <ThemeProvider attribute="class" defaultTheme="dark" enableSystem>
          <QueryClientProvider>
            <div className="max-w-screen overflow-x-hidden pt-14">
              <div className="fixed inset-x-0 top-0 z-10 border-b">
                <SiteHeader className="h-14" />
              </div>

              <React.Suspense>{children}</React.Suspense>
            </div>
          </QueryClientProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
